### ISSUE TITLE
Error - v0.3.4 - editorElement.getVisibleRowRange

### ISSUE THREAD

**Issue by mescribe0** [t9md/atom-quick-highlight#3]
Hello,
Yesterday I updated "quick-highlight" and since I encountered the following error:

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [quick-highlight](https://github.com/t9md/atom-quick-highlight) package, v0.3.4
### Stack Trace

Uncaught TypeError: editorElement.getVisibleRowRange is not a function

```
At /C:/Users/xtqm513/.atom/packages/quick-highlight/lib/main.coffee:110

TypeError: editorElement.getVisibleRowRange is not a function
  at getVisibleBufferRange (C:\Users\xtqm513\.atom\packages\quick-highlight\lib\main.coffee:62:38)
  at Object.module.exports.renderEditor (C:\Users\xtqm513\.atom\packages\quick-highlight\lib\main.coffee:141:31)
  at Object.module.exports.refreshEditor (C:\Users\xtqm513\.atom\packages\quick-highlight\lib\main.coffee:136:6)
  at Object.module.exports.toggle (C:\Users\xtqm513\.atom\packages\quick-highlight\lib\main.coffee:131:6)
  at atom-text-editor.subs.add.atom.commands.add.quick-highlight:toggle (C:\Users\xtqm513\.atom\packages\quick-highlight\lib\main.coffee:83:37)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\ProgramData\xtqm513\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at C:\ProgramData\xtqm513\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\ProgramData\xtqm513\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\ProgramData\xtqm513\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\ProgramData\xtqm513\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)

```
### Commands

```
     -2:36.6.0 quick-highlight:toggle (atom-text-editor.editor.is-focused)
     -1:53.6.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:53.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:52.6.0 core:select-right (atom-text-editor.editor.is-focused)
     -1:51.3.0 quick-highlight:toggle (atom-text-editor.editor.is-focused)
     -1:30.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:29 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:28.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.4.0 quick-highlight:toggle (atom-text-editor.editor)
     -1:26 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:24.8.0 quick-highlight:clear (atom-text-editor.editor)
     -1:22.4.0 quick-highlight:toggle (atom-text-editor.editor.is-focused)
     -0:19.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:18.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 quick-highlight:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-perlcritic",
      "SFTP-deployment",
      "keyboard-localization",
      "linter-perl"
    ]
  },
  "quick-highlight": {}
}
```
### Installed Packages

``` coffee
# User
atom-perl-prove, v0.5.0
compare-files, v0.6.2
editorconfig, v1.2.2
file-icons, v1.6.11
fold-functions, v0.4.3
highlight-column, v0.5.0
highlight-selected, v0.10.1
linter, v1.10.0
quick-highlight, v0.3.4
remote-sync, v3.1.2
Sublime-Style-Column-Selection, v1.3.0
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by t9md** [comment]
Sorry, its because v0.3.4 need to run Atom v1.1.0 above.
I should have specify supported engine version in package.json.

What you can do is 
- upgrade Atom to v1.1.0

or
-  apm install quick-highlight@0.3.2

Reference: To install specific  package version
https://discuss.atom.io/t/how-do-you-download-a-specific-version-of-a-package/11124/2

I will unpublish(remove) v0.3.3 and v0.3.4 after I release v0.3.5 which have correct engine version.

**Comment by t9md** [comment]
DONE unpublish, uninstall then reinstall should work for your atom version.
But I recommend you to update Atom v1.1.0 to use newer quick-highlight version. Its support selection on the fly highlight.

**Comment by mescribe0** [comment]
Thanks, I upgrade Atom to 1.1.0, and it works fine.
