### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by ghost** [t9md/atom-quick-highlight#6]
[Enter steps to reproduce below:]
1. Ctrl+shift+P to open the command pallet
2. Search with "quickhighlight"
3. Selecting the "Quick Hightlight: Toggle" from the autocomplete results below.

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [quick-highlight](https://github.com/t9md/atom-quick-highlight) package, v0.3.9
### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /home/george/.atom/packages/quick-highlight/lib/main.coffee:123

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at Object.module.exports.toggle (/home/george/.atom/packages/quick-highlight/lib/main.coffee:123:23)
    at atom-text-editor.subs.add.atom.commands.add.quick-highlight:toggle (/home/george/.atom/packages/quick-highlight/lib/main.coffee:84:4)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:45 snippets:expand (atom-text-editor.editor.is-focused)
     -0:45 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:45 editor:indent (atom-text-editor.editor.is-focused)
  5x -0:44 core:backspace (atom-text-editor.editor.is-focused)
     -0:42.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.6.0 settings-view:show-keybindings (atom-text-editor.editor.is-focused)
     -0:27.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:26.2.0 core:undo (atom-text-editor.editor.mini.is-focused)
  5x -0:21.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:11.2.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
  2x -0:05.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 quick-highlight:toggle (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "ignoredNames": [
      ".git"
    ],
    "projectHome": "/home/george/workspace",
    "disabledPackages": [
      "atom-jshint",
      "color-picker"
    ]
  },
  "quick-highlight": {
    "countDisplayPosition": "Right"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.9.1
docblockr, v0.7.3
linter, v1.11.3
linter-htmlhint, v0.2.1
linter-js-standard, v3.2.1
linter-jshint, v1.2.1
linter-markdown, v1.2.1
linter-phpcs, v1.3.0
linter-sass-lint, v0.4.1
markdown-preview-plus, v2.2.2
minimap, v4.16.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
project-manager, v2.6.5
quick-highlight, v0.3.9

# Dev
No dev packages
```

**Comment by t9md** [comment]
I can't reproduce this issue? Is this always happen or occasional issue?
Need more narrowed condition this error happen.

**Comment by ghost** [comment]
@t9md Hmmm after re-installing the plugin i can't reproduced it either in the office desktop, I'll re-try it at my laptop as well and I'll get back to you.
You might be right that this could be occasional.

**Comment by t9md** [comment]
This is a bit old, and seem to no update, not sure this is still problem or not.
Reopen if so.
